[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nonebot-plugin-mystool"
version = "0.1.0"
authors = [
  { name="Ljzd-PRO", email="ljzd@office.ljzd-pro.ml" },
  { name="Everything0519", email="598139245@qq.com" },
]
description = "NoneBot插件|米游社工具-每日米游币任务、游戏签到、商品兑换、免抓包登录"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx",
    "nonebot_plugin_apscheduler",
    "ntplib",
    "Pillow",
    "requests",
    "nonebot_adapter_onebot",
]

[project.urls]
"Homepage" = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool"
"Bug Tracker" = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool/issues"
"Wiki" = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool/wiki"
