[tool.poetry]
name = "nonebot-plugin-mystool"
version = "0.1.0"
description = "NoneBot插件|米游社工具-每日米游币任务、游戏签到、商品兑换、免抓包登录"
license = "MIT"
authors = [
  "Ljzd-PRO <ljzd@office.ljzd-pro.ml>",
  "Everything0519 <598139245@qq.com>",
]
readme = "README.md"
homepage = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool"
repository = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool"
documentation = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool/wiki"
keywords = ["bot", "qq", "qqbot", "mirai", "coolq", "nonebot", "mihoyo", "mihoyobbs"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: Chinese",
]
packages = [
    { include = "nonebot-plugin-mystool", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.22.0"
nonebot_plugin_apscheduler = "*"
ntplib = "*"
Pillow = ">=9.1.1"
requests = "*"
nonebot_adapter_onebot = "*"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Ljzd-PRO/nonebot-plugin-mysTool/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
